# submission4のパラメータ
# tfidfを追加した

# 推論時のconfigであることを指定
phase: baseline

# PATH
input_path: ../input/
output_path: ../output/
train_csv_path: ../input/train.csv
test_csv_path: ../input/test.csv
train_images_dir_path: ../input/train_images

# primary_key
primary_key:
  LOAN_ID: category

# n_splits
n_splits: 5

# random_state
random_state: 0

# 予測対象の列
target: LOAN_AMOUNT_log1p

# model weight計算時に使用する列
weight_column: 

# sentence
sentence_columns:
  - DESCRIPTION_TRANSLATED
  - LOAN_USE

# 特徴量
feature_columns:
  ORIGINAL_LANGUAGE: category
  ACTIVITY_NAME: category
  SECTOR_NAME: category
  COUNTRY_NAME: category
  CURRENCY_POLICY: category
  CURRENCY: category
  REPAYMENT_INTERVAL: category
  DESCRIPTION_TRANSLATED_char_count: float16
  DESCRIPTION_TRANSLATED_word_count: float16
  DESCRIPTION_TRANSLATED_word_unique_count: float16
  DESCRIPTION_TRANSLATED_word_unique_ratio: float16
  DESCRIPTION_TRANSLATED_word_ave_length: float16
  DESCRIPTION_TRANSLATED_punc_count: float16
  DESCRIPTION_TRANSLATED_uppercase: float16
  DESCRIPTION_TRANSLATED_lowercase: float16
  DESCRIPTION_TRANSLATED_up_low_ratio: float16
  DESCRIPTION_TRANSLATED_sentence_count: float16
  DESCRIPTION_TRANSLATED_sentence_ave_length: float16
  DESCRIPTION_TRANSLATED_sentence_max_length: float16
  DESCRIPTION_TRANSLATED_sentence_min_length: float16
  DESCRIPTION_TRANSLATED_word_per_sentence: float16
  DESCRIPTION_TRANSLATED_syllable_count: float16
  DESCRIPTION_TRANSLATED_syllable_per_sentence: float16
  DESCRIPTION_TRANSLATED_syllable_per_word: float16
  DESCRIPTION_TRANSLATED_flesch_reading_ease_score: float16
  DESCRIPTION_TRANSLATED_gunning_fog_score: float16
  DESCRIPTION_TRANSLATED_smog_index_score: float16
  LOAN_USE_char_count: float16
  LOAN_USE_word_count: float16
  LOAN_USE_word_unique_count: float16
  LOAN_USE_word_unique_ratio: float16
  LOAN_USE_word_ave_length: float16
  LOAN_USE_punc_count: float16
  LOAN_USE_uppercase: float16
  LOAN_USE_lowercase: float16
  LOAN_USE_up_low_ratio: float16
  LOAN_USE_sentence_count: float16
  LOAN_USE_sentence_ave_length: float16
  LOAN_USE_sentence_max_length: float16
  LOAN_USE_sentence_min_length: float16
  LOAN_USE_word_per_sentence: float16
  LOAN_USE_syllable_count: float16
  LOAN_USE_syllable_per_sentence: float16
  LOAN_USE_syllable_per_word: float16
  LOAN_USE_flesch_reading_ease_score: float16
  LOAN_USE_gunning_fog_score: float16
  TFIDF_1_TAGS: float32
  TFIDF_2_TAGS: float32
  TFIDF_1_LOAN_USE: float32
  TFIDF_2_LOAN_USE: float32

# lgbのハイパーパラメータ
lgb_hyper_params:
  metric: rmse
  objective: regression
  learning_rate: 0.1
  min_data_in_leaf: 10
  num_leaves: 63
  max_depth: 7
  bagging_fraction: 0.8
  feature_fraction: 0.8
  lambda_l1: 5
  lambda_l2: 5
  random_state: 42
  verbose: -1

# lgb_adversarial_validation_hyper_params
AdversarialValidation:
  target: AdvVal_y
  lgb_hyper_params:
    metric: auc
    objective: binary
    learning_rate: 0.01
    min_data_in_leaf: 10
    num_leaves: 63
    max_depth: 7
    bagging_fraction: 0.8
    feature_fraction: 0.8
    lambda_l1: 5
    lambda_l2: 5
    random_state: 42
    verbose: -1

# lgb学習時のパラメータ
lgb_train_config:
  num_iterations: 20000
  verbose_eval: 1000
  early_stopping: 100
  category_cols:
    - ORIGINAL_LANGUAGE
    - ACTIVITY_NAME
    - SECTOR_NAME
    - COUNTRY_NAME
    - CURRENCY_POLICY
    - CURRENCY
    - REPAYMENT_INTERVAL

# optunaのパラメータ
lgb_optuna_config:
  verbose_eval: 1000
  early_stopping_rounds: 100
  fixed_params:
    boosting_type: gbdt
    objective: regression
    metric: rmse
    verbosity: -1

# cat
cat_hyper_params:
  loss_function: RMSE
  num_boost_round: 5000
  early_stopping_rounds: 100
  verbose: -1
  depth: 6
  learning_rate: 0.03

cat_train_config:
  verbose: 1000
  plot: False  # plotlyが描画される
  cat_features:
    - List
    - Sector
    - Industry

# xgboost
xgb_hyper_params:
  booster: gbtree
  objective: reg:squarederror
  eval_metric: rmse
  eta: 0.3  # default=0.3
  max_depth: 6  # default=6
  min_child_weight: 1  # default=1
  gamma: 0.0  # default=0
  colsample_bytree: 0.8  # default=1
  subsample: 0.8  # default=1
  alpha: 0  # default=0
  lambda: 1  # default=1
  random_state: 0

xgb_train_config:
  num_boost_round: 5000
  early_stopping_rounds: 100
  enable_categorical: True
  verbose_eval: 1000